version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_node
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lembretes_db
      MYSQL_USER: lembretes
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: node_app
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   environment:
  #     DB_NAME: ${DB_NAME}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_HOST: db
  #     DB_PORT: 3306
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/app

volumes:
  db_data:
